name = "fractional-reserve-sxt-worker"
main = "src/worker.js"
compatibility_date = "2023-05-22"
compatibility_flags = [ "nodejs_compat" ]
nodejs_compat = true

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

[env.production.vars]
PUBLIC_KEY="0xd31c9f02e2a3fE53DC84A17e79E57B5156014644"
USER_ID="instruxi-001"
API_URL="https://api.spaceandtime.app/v1/"
RESOURCE_ID="INSTRUXI.IONI_AUDIT"
SQL_TEXT="SELECT sum(audited_gold_amount) as total_reserve FROM INSTRUXI.IONI_AUDIT WHERE audited=true"
AUTH_SCHEME="1"

[env.staging.vars]
PUBLIC_KEY="0xd31c9f02e2a3fE53DC84A17e79E57B5156014644"
PRIVATE_KEY=""
USER_ID="instruxi-001"
API_URL="https://api.spaceandtime.app/v1/"
RESOURCE_ID="INSTRUXI.IONI_AUDIT"
SQL_TEXT="SELECT sum(audited_gold_amount) as total_reserve FROM INSTRUXI.IONI_AUDIT WHERE audited=true"
AUTH_SCHEME="1"

# [env.shared]
# PUBLIC_KEY="0xd31c9f02e2a3fE53DC84A17e79E57B5156014644"
# USER_ID="instruxi-001"
# API_URL="https://api.spaceandtime.app/v1/"
# RESOURCE_ID="INSTRUXI.IONI_AUDIT"
# SQL_TEXT="SELECT sum(audited_gold_amount) as total_reserve FROM INSTRUXI.IONI_AUDIT WHERE audited='true'"
# AUTH_SCHEME="1"

